Content-Type: multipart/mixed; boundary="===============0597270683816009526=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 09:28:33 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348113.6927872@test.net

--===============0597270683816009526==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like unicorns!
--===============0597270683816009526==--

