Content-Type: multipart/mixed; boundary="===============0161358383287834961=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 10:01:22 +0700
Subject: Fishes
Cc: 
Bcc: 
Message-ID: 1702350082.3098154@test.net

--===============0161358383287834961==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Do you like fishes?
--===============0161358383287834961==--

