Content-Type: multipart/mixed; boundary="===============6404526586706295084=="
MIME-Version: 1.0
From: person1@test.net
To: person1@test.net
Date: Tue, 05 Dec 2023 19:15:46 +0700
Subject: 
Cc: 
Bcc: 
Message-ID: 1701778546.5810668@test.net

--===============6404526586706295084==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello!
--===============6404526586706295084==--

