Content-Type: multipart/mixed; boundary="===============5066676777799587269=="
MIME-Version: 1.0
From: person1@test.net
To: person1@test.net
Date: Fri, 08 Dec 2023 09:31:07 +0700
Subject: Hello
Cc: 
Bcc: 
Message-ID: 1702002667.4263902@test.net

--===============5066676777799587269==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Meeting starts tomorrow!
--===============5066676777799587269==--

