Content-Type: multipart/mixed; boundary="===============1207848380298734862=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 09:28:31 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348111.3820891@test.net

--===============1207848380298734862==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like unicorns!
--===============1207848380298734862==--

