Content-Type: multipart/mixed; boundary="===============3662344457315256671=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 09:28:43 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348123.979091@test.net

--===============3662344457315256671==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like unicorns!
--===============3662344457315256671==--

