Content-Type: multipart/mixed; boundary="===============5014221572402099976=="
MIME-Version: 1.0
From: person1@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 21:10:00 +0700
Subject: Another test mail
Cc: 
Message-ID: 1702390200.6300836@test.net

--===============5014221572402099976==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit


--===============5014221572402099976==--

