Content-Type: multipart/mixed; boundary="===============6867311944579973674=="
MIME-Version: 1.0
From: person1@testmail.net
To: person1@testmail.net
Date: Tue, 12 Dec 2023 21:34:59 +0700
Subject: test mail for the project
Cc: 
Bcc: 
Message-ID: 1702391699.8077018@testmail.net

--===============6867311944579973674==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

sample content
--===============6867311944579973674==--

