Content-Type: multipart/mixed; boundary="===============8049435718478408622=="
MIME-Version: 1.0
From: person1@testmail.net
To: person2@testmail.net
Date: Tue, 12 Dec 2023 21:53:33 +0700
Subject: ASAP
Cc: person3@testmail.net
Bcc: 
Message-ID: 1702392813.9010303@testmail.net

--===============8049435718478408622==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

finish the report
--===============8049435718478408622==--

