Content-Type: multipart/mixed; boundary="===============5976552503153558538=="
MIME-Version: 1.0
From: sender@test.net
To: person3@test.net
Date: Fri, 24 Nov 2023 21:56:56 +0700
Subject: Text Test
Cc: 
Bcc: 

--===============5976552503153558538==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

text attachment test
--===============5976552503153558538==
Content-Type: application/octet-stream; Name="TextTest1.txt"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="TextTest1.txt"

SGV5LCBkbyB5b3Ugc2VlIHRoaXM/DQpJZiB5b3UgZG8sIHRoYXQncyBncmVhdCE=

--===============5976552503153558538==--

