20231212093151968.msg
1
sender:person1@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============3023971474338070005=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:51 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348311.953662@test.net

--===============3023971474338070005==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============3023971474338070005==--

.
