20231212093152297.msg
1
sender:person1@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============2046071468388933268=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:52 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348312.2824736@test.net

--===============2046071468388933268==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============2046071468388933268==--

.
