20231212093152468.msg
1
sender:person1@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============7400291772593131657=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:52 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348312.451377@test.net

--===============7400291772593131657==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============7400291772593131657==--

.
