20231212093147507.msg
1
sender:person1@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============5030347197523136533=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:47 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348307.492225@test.net

--===============5030347197523136533==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============5030347197523136533==--

.
