20231129184959800.msg
sender:person1@test.net
Content-Type: multipart/mixed; boundary="===============2980343673734990118=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Wed, 29 Nov 2023 18:49:59 +0700
Subject: Alo alo
Cc: person3@test.net
Bcc: 
Message-ID: 1701258599.7747324@test.net

--===============2980343673734990118==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello !
--===============2980343673734990118==--

.
