20231212133554087.msg
0
sender:person1@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============2605462620069543075=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 13:35:54 +0700
Subject: Hi
Cc: 
Message-ID: 1702362954.0770097@test.net

--===============2605462620069543075==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello World!
--===============2605462620069543075==--

.
