20231212105514563.msg
1
sender:person2@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============7551142770997034183=="
MIME-Version: 1.0
From: person2@test.net
To: 
Date: Tue, 12 Dec 2023 10:55:14 +0700
Subject: Fishes
Cc: 
Bcc: person1@test.net, person2@test.net, person3@test.net
Message-ID: 1702353314.5515358@test.net

--===============7551142770997034183==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Do you like fishes?
--===============7551142770997034183==--

.
