20231212093149179.msg
1
sender:person1@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============6899297625328420650=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:49 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348309.1622653@test.net

--===============6899297625328420650==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============6899297625328420650==--

.
