20231123094020661.msg
sender:sender@test.net
Content-Type: multipart/mixed; boundary="===============7263575556709635689=="
MIME-Version: 1.0
From: sender@test.net
To: person1@test.net
Date: Thu, 23 Nov 2023 09:40:20 +0700
Subject: Hi
Cc: person2@test.net
Bcc: person3@test.net

--===============7263575556709635689==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello
--===============7263575556709635689==--

.
