20231212093148625.msg
1
sender:person1@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============2336786077597981581=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:48 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348308.6105864@test.net

--===============2336786077597981581==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============2336786077597981581==--

.
