20231212093151527.msg
1
sender:person1@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============3938888211029004215=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:51 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348311.512915@test.net

--===============3938888211029004215==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============3938888211029004215==--

.
