Content-Type: multipart/mixed; boundary="===============3797859348334207287=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:34 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348294.9723036@test.net

--===============3797859348334207287==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============3797859348334207287==--

