Content-Type: multipart/mixed; boundary="===============4340842463487441837=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:48 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348308.0509038@test.net

--===============4340842463487441837==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============4340842463487441837==--

