Content-Type: multipart/mixed; boundary="===============2505470979651654051=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:32 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348292.472644@test.net

--===============2505470979651654051==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============2505470979651654051==--

