Content-Type: multipart/mixed; boundary="===============0978336933359877870=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:50 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348310.7773368@test.net

--===============0978336933359877870==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============0978336933359877870==--

