Content-Type: multipart/mixed; boundary="===============4656006526180454352=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:46 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348306.9075413@test.net

--===============4656006526180454352==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============4656006526180454352==--

