Content-Type: multipart/mixed; boundary="===============2611461990918675040=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 13:38:03 +0700
Subject: Hi
Cc: 
Message-ID: 1702363083.8207521@test.net

--===============2611461990918675040==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello World!
--===============2611461990918675040==--

