Content-Type: multipart/mixed; boundary="===============6387057961948331152=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:51 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348311.8097484@test.net

--===============6387057961948331152==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============6387057961948331152==--

