Content-Type: multipart/mixed; boundary="===============0061828664632744071=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 10:54:55 +0700
Subject: Fishes
Cc: 
Bcc: person2@test.net, person3@test.net
Message-ID: 1702353295.0954273@test.net

--===============0061828664632744071==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Do you like fishes?
--===============0061828664632744071==--

