Content-Type: multipart/mixed; boundary="===============1946814169006116917=="
MIME-Version: 1.0
From: person1@test.net
To: person2@test.net
Date: Tue, 12 Dec 2023 09:31:49 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348309.7389402@test.net

--===============1946814169006116917==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like apples!
--===============1946814169006116917==--

