20231208093656722.msg
1
sender:person1@test.net;folder:inbox,project,important,weird
Content-Type: multipart/mixed; boundary="===============6536339738669537165=="
MIME-Version: 1.0
From: person1@test.net
To: person1@test.net
Date: Fri, 08 Dec 2023 09:36:56 +0700
Subject: Helol
Cc: 
Bcc: 
Message-ID: 1702003016.7019236@test.net

--===============6536339738669537165==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like unicorn, reply ASAP
--===============6536339738669537165==--

.
