20231212094727515.msg
0
sender:person2@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============1307924765805659904=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 09:47:27 +0700
Subject: This is another spam e-mail
Cc: person2@test.net, person3@test.net
Bcc: 
Message-ID: 1702349247.4920897@test.net

--===============1307924765805659904==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello, what's your bank account's password?
--===============1307924765805659904==--

.
