20231212221902575.msg
1
sender:person1@test.net;folder:inbox,project,important
Content-Type: multipart/mixed; boundary="===============7031267546299564994=="
MIME-Version: 1.0
From: person1@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 22:19:02 +0700
Subject: Hello
Cc: 
Message-ID: 1702394342.5672956@test.net

--===============7031267546299564994==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

How are you? ASAP
--===============7031267546299564994==--

.
