20231207083939777.msg
0
sender:person1@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============1324852976160986177=="
MIME-Version: 1.0
From: person1@test.net
To: person1@test.net
Date: Thu, 07 Dec 2023 08:39:39 +0700
Subject: Hello
Cc: 
Bcc: 
Message-ID: 1701913179.765739@test.net

--===============1324852976160986177==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

HI!
--===============1324852976160986177==--

.
