20231212133238854.msg
1
sender:person2@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============8693510702771285573=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 13:32:38 +0700
Subject: Hi
Cc: 
Message-ID: 1702362758.8199267@test.net

--===============8693510702771285573==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello World!
--===============8693510702771285573==--

.
