20231212094700631.msg
0
sender:person2@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============2336627804115519643=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 09:47:00 +0700
Subject: This is another spam e-mail
Cc: 
Bcc: 
Message-ID: 1702349220.610434@test.net

--===============2336627804115519643==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello, what's your bank account's password?
--===============2336627804115519643==--

.
