20231212095951312.msg
0
sender:person2@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============7567041370880281400=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 09:59:51 +0700
Subject: Stairs
Cc: 
Bcc: 
Message-ID: 1702349991.2883894@test.net

--===============7567041370880281400==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I hate stairs, they're always up to something.
--===============7567041370880281400==--

.
