20231212092844698.msg
1
sender:person2@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============5717915963781240161=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 09:28:44 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348124.6827207@test.net

--===============5717915963781240161==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like unicorns!
--===============5717915963781240161==--

.
