20231212092835905.msg
1
sender:person2@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============8293627822527335447=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 09:28:35 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348115.8915544@test.net

--===============8293627822527335447==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like unicorns!
--===============8293627822527335447==--

.
