20231212221901337.msg
1
sender:person1@test.net;folder:inbox,project,important
Content-Type: multipart/mixed; boundary="===============1581089236283742141=="
MIME-Version: 1.0
From: person1@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 22:19:01 +0700
Subject: Hello
Cc: 
Message-ID: 1702394341.3226366@test.net

--===============1581089236283742141==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

How are you? ASAP
--===============1581089236283742141==--

.
