20231212092842913.msg
1
sender:person2@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============9163826497176935157=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 09:28:42 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348122.8986409@test.net

--===============9163826497176935157==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like unicorns!
--===============9163826497176935157==--

.
