20231123093649956.msg
1
sender:sender@test.net;folder:inbox
Content-Type: multipart/mixed; boundary="===============8577466639718439228=="
MIME-Version: 1.0
From: sender@test.net
To: person1@test.net
Date: Thu, 23 Nov 2023 09:36:49 +0700
Subject: Hello
Cc: person2@test.net
Bcc: person3@test.net

--===============8577466639718439228==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hi
--===============8577466639718439228==--

.
