20231212221902237.msg
1
sender:person1@test.net;folder:inbox,project,important
Content-Type: multipart/mixed; boundary="===============3800322620520294215=="
MIME-Version: 1.0
From: person1@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 22:19:02 +0700
Subject: Hello
Cc: 
Message-ID: 1702394342.2277741@test.net

--===============3800322620520294215==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

How are you? ASAP
--===============3800322620520294215==--

.
