20231204225615263.msg
1
sender:sender@test.net;folder:Spam
Content-Type: multipart/mixed; boundary="===============5956465800476940971=="
MIME-Version: 1.0
From: sender@test.net
To: person1@test.net
Date: Mon, 04 Dec 2023 22:56:15 +0700
Subject: Hi ASAP
Cc: 
Bcc: 
Message-ID: 1701705375.233145@test.net

--===============5956465800476940971==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

HI virus
--===============5956465800476940971==--

.
