20231205071034705.msg
1
sender:sender@test.net;folder:Important
Content-Type: multipart/mixed; boundary="===============7324823796508320313=="
MIME-Version: 1.0
From: sender@test.net
To: person1@test.net
Date: Tue, 05 Dec 2023 07:10:34 +0700
Subject: GIve me the code ASAP
Cc: person1@test.net,person2@test.net
Bcc: 
Message-ID: 1701735034.6812096@test.net

--===============7324823796508320313==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

This is urgent!!!
--===============7324823796508320313==--

.
