20231212092834506.msg
1
sender:person2@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============3200274574328604488=="
MIME-Version: 1.0
From: person2@test.net
To: person1@test.net
Date: Tue, 12 Dec 2023 09:28:34 +0700
Subject: This is a spam e-mail
Cc: 
Bcc: 
Message-ID: 1702348114.4913309@test.net

--===============3200274574328604488==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I like unicorns!
--===============3200274574328604488==--

.
