20231207083816680.msg
0
sender:person1@test.net;folder:inbox,project
Content-Type: multipart/mixed; boundary="===============2024421202234477660=="
MIME-Version: 1.0
From: person1@test.net
To: person1@test.net
Date: Thu, 07 Dec 2023 08:38:16 +0700
Subject: Hello
Cc: 
Bcc: 
Message-ID: 1701913096.6705916@test.net

--===============2024421202234477660==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hacked
--===============2024421202234477660==--

.
