20231208121719407.msg
1
sender:person3@test.net;folder:inbox,spam
Content-Type: multipart/mixed; boundary="===============4064575463650862157=="
MIME-Version: 1.0
From: person3@test.net
To: person3@test.net
Date: Fri, 08 Dec 2023 12:17:19 +0700
Subject: Hey
Cc: 
Bcc: 
Message-ID: 1702012639.3855262@test.net

--===============4064575463650862157==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

I'm a virus
--===============4064575463650862157==--

.
